### ISSUE TITLE
TypeParameter multiple key setting shortcut fails after attaching

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1068]
## Description

The shortcut syntax to set the parameters for multiple types throws an exception when used after attaching.

## Script

```python
import hoomd

cpu = hoomd.device.CPU()
sim = hoomd.Simulation(device=cpu, seed=1)
sim.create_state_from_gsd(filename='init.gsd')

integrator = hoomd.md.Integrator(dt=0.005)
cell = hoomd.md.nlist.Cell()
lj = hoomd.md.pair.LJ(nlist=cell)

particle_types = sim.state.particle_types
lj.params[(particle_types, particle_types)] = dict(epsilon=1, sigma=1)
lj.r_cut[(particle_types, particle_types)] = 2.5
integrator.forces.append(lj)
nvt = hoomd.md.methods.NVT(kT=1.5, filter=hoomd.filter.All(), tau=1.0)
integrator.methods.append(nvt)

sim.operations.integrator = integrator

sim.run(0)

lj.params[(particle_types, particle_types)] = dict(epsilon=1, sigma=2)
lj.r_cut[(particle_types, particle_types)] = 5
```
Note: `init.gsd` has particle types `['A', 'B']`

## Output

```
Traceback (most recent call last):
  File "/Users/joaander/test/charge-pppm/test-params.py", line 22, in <module>
    lj.params[(particle_types, particle_types)] = dict(epsilon=1, sigma=2)
  File "/Users/joaander/build/hoomd/hoomd/data/typeparam.py", line 35, in __setitem__
    self.param_dict[key] = value
  File "/Users/joaander/build/hoomd/hoomd/data/parameterdicts.py", line 266, in __setitem__
    for key in keys:
  File "/Users/joaander/build/hoomd/hoomd/data/parameterdicts.py", line 274, in _yield_keys
    raise KeyError("Type {} does not exist in the "
KeyError: "Type ('A', 'B') does not exist in the system."
```

## Expected output

No error.

## Configuration

Platform:
- Mac
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.9.6
- **HOOMD-blue** version: `master` branch

## Developer

@b-butler can you look into this?

**Comment by joaander** [comment]
[init.gsd.gz](https://github.com/glotzerlab/hoomd-blue/files/6877326/init.gsd.gz)
