### ISSUE TITLE
Periodic potential field does not work in two dimensional box

### ISSUE THREAD

**Issue by KevinModica** [glotzerlab/hoomd-blue#1475]
### Description

When implementing the hoomd.md.external.field.Periodic() force on a two dimensional system, the forces are NaN due to a divide by zero error in the evalForceEnergyAndVirial() method. This seems to arise from the V_box = m_box.getVolume() not correctly flagging the box as two-dimensional and returning a zero volume instead of a nonzero area.  

Evaluator file for the periodic potential:
https://github.com/glotzerlab/hoomd-blue/blob/v3.8.1/hoomd/md/EvaluatorExternalPeriodic.h#L133

Relevant getVolume() method for a box:
https://github.com/glotzerlab/hoomd-blue/blob/v3.8.1/hoomd/BoxDim.h#L558-L564

### Script

```python
import hoomd
import gsd.hoomd
import gsd
import hoomd.md
import numpy as np
import datetime


###INSERTVARIABLES
TTOT_input=100.0
tsamp_input=1
dt_input=0.001




# Boilerplate and Derived variables
gamma = 1
sigma = 1
epsilon = 1
mass = 1
kT = 1
r_buff = 0.0 # buffer radius around the cutoff (for neighborlist update)
# (note that 2*(r_cut + r_buff) < L has to be satisfied)


# Helper Functions
class Status():
    def __init__(self, sim):
        self.sim = sim
    @property
    def seconds_remaining(self):
        try:
            return (self.sim.final_timestep - self.sim.timestep) / self.sim.tps
        except ZeroDivisionError:
            return 0

    @property
    def etr(self):
        return str(datetime.timedelta(seconds=self.seconds_remaining))



# Design the Initial Snapshot
s = gsd.hoomd.Snapshot()
s.particles.N = 1
s.particles.types=['A']
s.particles.typeid=[0]
s.particles.position = [0,0,0]
s.configuration.dimensions = 2
s.configuration.box = [20, 20, 1, 0, 0, 0]



f = gsd.hoomd.open(name='init_ABP.gsd',mode="wb")
f.append(s)
f.close()



#### Activate Device and Instatiate a Simulation
gpu = hoomd.device.CPU()
sim = hoomd.Simulation(device=gpu,seed=1)
sim.create_state_from_gsd(filename='init_ABP.gsd')

#### Set up brownian translational motion
brownian = hoomd.md.methods.Brownian(filter=hoomd.filter.All(), kT=kT)
# set drag coeffs for each particle type
brownian.gamma['A'] = gamma

#### Set up forces
cell = hoomd.md.nlist.Cell(r_buff)
pairpot = hoomd.md.pair.LJ(nlist=cell, default_r_cut=float(2.0**(1.0/6.0)*sigma), mode='shift')
pairpot.params[('A','A')] = {'sigma':sigma, 'epsilon':1}




periodicForce = hoomd.md.external.field.Periodic()
periodicForce.params['A'] = dict(A=0.01,i=0,w=10,p=1)
  
integrator = hoomd.md.Integrator(dt=dt_input,
                                     methods=[brownian],
                                     forces = [periodicForce,pairpot]
                                     )
sim.operations += integrator



#### Set up gsd writing and logging
trigger2 = hoomd.trigger.Periodic(period=int(tsamp_input))
logforce = hoomd.logging.Logger()

gsd_writer = hoomd.write.GSD(filename='dump.gsd',
					   		 trigger=trigger2,
					   		 mode='wb', 
							 dynamic=['momentum'],
                             log=logforce)

logger = hoomd.logging.Logger(categories=['scalar', 'string'])
logger.add(sim, quantities=['timestep', 'tps'])
status = Status(sim)
logger[('Status', 'etr')] = (status, 'etr', 'string')
table = hoomd.write.Table(trigger=hoomd.trigger.Periodic(period=int(np.ceil(TTOT_input/500))),
                          logger=logger)
sim.operations.writers.append(table)


print('Starting Simulation')
sim.operations += gsd_writer

sim.run(TTOT_input)
```

### Output

```shell
Starting Simulation
**ERROR**: Particle with unique tag 0 has NaN for its position.
Traceback (most recent call last):
  File "examplePeriodicFieldError.py", line 112, in <module>
    sim.run(TTOT_input)
  File "/opt/glotzerlab/lib/python3.9/site-packages/hoomd/simulation.py", line 462, in run
    self._cpp_sys.run(steps_int, write_at_start)
RuntimeError: Error computing cell list
```

### Platform

CPU, GPU, Linux

### Installation method

glotzerlab-software container

### HOOMD-blue version

3.8.1

### Python version

3.10.6

**Comment by joaander** [comment]
This (and possibly mode) code also needs to be changed to support 2D:
https://github.com/glotzerlab/hoomd-blue/blob/925a73946736b4e77d31ba95c182b676798599bf/hoomd/md/EvaluatorExternalPeriodic.h#L165-L168
It is taking a 3D cross product of two box vectors. In 2D, there are only 2 box vectors and the cross product is not defined.
