### ISSUE TITLE
GSD error running Hard particle Monte Carlo

### ISSUE THREAD

**Issue by zhangruoyao68** [glotzerlab/hoomd-blue#1661]
### Description

After a fresh installation of hoomd-4.3.0 in Miniforge3, I was trying to run the Hard particle Monte Carlo example on homepage. A runtime GSD error occurred. Could you help take a look? Thank you!

### Script

```python
import hoomd

mc = hoomd.hpmc.integrate.ConvexPolyhedron()
mc.shape['octahedron'] = dict(vertices=[
    (-0.5, 0, 0),
    (0.5, 0, 0),
    (0, -0.5, 0),
    (0, 0.5, 0),
    (0, 0, -0.5),
    (0, 0, 0.5),
])

cpu = hoomd.device.CPU()
sim = hoomd.Simulation(device=cpu, seed=20)
sim.operations.integrator = mc
# The tutorial describes how to construct an initial configuration 'init.gsd'.
sim.create_state_from_gsd(filename='init.gsd')

sim.run(1e5)
```

### Output

```shell
(base) ➜ python test.py
Traceback (most recent call last):
  File "/home/rz/hoomd/test.py", line 17, in <module>
    sim.create_state_from_gsd(filename='init.gsd')
  File "/home/rz/miniforge3/lib/python3.10/site-packages/hoomd/simulation.py", line 230, in create_state_from_gsd
    reader = _hoomd.GSDReader(self.device._cpp_exec_conf, filename,
RuntimeError: GSD: No such file or directory - init.gsd
```

### Platform

CPU

### Installation method

Conda package

### HOOMD-blue version

4.3.0

### Python version

3.10.12

**Comment by joaander** [comment]
For future reference, the error message "No such file or directory - init.gsd" indicates that the file does not exist.
