### ISSUE TITLE
hoomd.hdf5.query

### ISSUE THREAD

**Issue by InnocentBug** [glotzerlab/hoomd-blue#436]
## Description

Querying a 

## Script

```python
# Include a minimal script that reproduces the problem

```

## Output
external.py:048  |      log = hoomd.hdf5.log(f,matrix_quantities=["density_fields"],period=1)
Traceback (most recent call last):
  File "./external.py", line 49, in <module>
    density = log.query("density_fields")
  File "/net/theorie/auto/scratch2/ludwig/hoomdstuff/v2/installCPU/hoomd/hdf5.py", line 169, in query
    return self.cpp_analyzer.getMatrixQuantity(quantity, timestep, use_cache)
TypeError: getMatrixQuantity(): incompatible function arguments. The following argument types are supported:
    1. (self: hoomd._hoomd.LogMatrix, arg0: str, arg1: int) -> array

Invoked with: <hoomd._hoomd.LogHDF5 object at 0x7ff154508e30>, 'density_fields', 10, True

## Expected output

external.py:048  |      log = hoomd.hdf5.log(f,matrix_quantities=["density_fields"],period=1)

## Configuration

All configurations.

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
I tested with a build from source, but should affect all builds.

Versions:
- Python version: 3.7.3
- **HOOMD-blue** version: v2.6.0-7-g60513d253 DOUBLE HPMC_MIXED MPI SSE SSE2

## Developer

I fixed the problem and submit a PR in a minute.

**Comment by InnocentBug** [comment]
I submitted a PR #437
