### ISSUE TITLE
Eliminate or rename context.initialize()

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#473]
## Description

The `context.initialize()`call in `next` is confusing. It clearly is a legacy of HOOMD 2.x, but doesn't accept the same arguments anymore. Users get a not so helpful error message when they try to pass command line options to `context.initialize()`, which are no longer supported. I propose to get rid of the function in favor of a simple constructor call to `hoomd.context.SimulationContext()`. If there are reasons for which we might want to keep the function call, it could be renamed to clearly indicate the different API.

## Script

```python
# Include a minimal script that reproduces the problem
import hoomd
hoomd.context.initialize('--mode=-gpu') #<- wrong
```

## Output

```
>>> import hoomd
>>> hoomd.context.initialize('--mode=-gpu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/context.py", line 206, in initialize
    cite._ensure_global_bib()
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/cite.py", line 434, in _ensure_global_bib
    hoomd.context.bib.add([hoomd_base, hoomd_mpi])
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/cite.py", line 337, in add
    hoomd.context.current.device.cpp_msg.notice(1, cite_str)
AttributeError: 'str' object has no attribute 'cpp_msg'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/__init__.py", line 84, in _hoomd_sys_excepthook
    _hoomd.abort_mpi(context.current.device.cpp_exec_conf);
AttributeError: 'str' object has no attribute 'cpp_exec_conf'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/context.py", line 206, in initialize
    cite._ensure_global_bib()
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/cite.py", line 434, in _ensure_global_bib
    hoomd.context.bib.add([hoomd_base, hoomd_mpi])
  File "/nfs/turbo/bi-vislab/jsglaser/miniconda3/envs/myenv/lib/python3.7/site-packages/hoomd/cite.py", line 337, in add
    hoomd.context.current.device.cpp_msg.notice(1, cite_str)
AttributeError: 'str' object has no attribute 'cpp_msg'
```

## Expected output

```AttributeError: module 'hoomd.context' has no attribute 'initialize'```

## Configuration

Versions:
- Python version: 3.7
- **HOOMD-blue** version: `next`,  https://github.com/glotzerlab/hoomd-blue/commit/e5070eba5923df6715fe3fb5cc25e582e9167d40

## Developer

perhaps. This can be addressed as part of the planned API overhaul in #395

**Comment by joaander** [comment]
Yes, we will remove `context.initialize()` as part of #395. This has always been part of the plan.
