### ISSUE TITLE
FENE bonds bug

### ISSUE THREAD

**Issue by astatt** [glotzerlab/hoomd-blue#941]
## Description

The fene bonds appear to have a bug in v3-beta.4.   It looks like a lj is used to compute the fene potential internally but it's not correctly registered, leading to a KeyError. 

## Script

```python
import hoomd
import hoomd.md
import gsd.hoomd

gpu = hoomd.device.GPU(notice_level=2)

sim = hoomd.Simulation(device=gpu)

snapshot = gsd.hoomd.Snapshot()
snapshot.particles.N = 2
snapshot.particles.position = [(0,0,0),(0.969,0,0)]
snapshot.configuration.box = [5, 5, 5, 0, 0, 0]
snapshot.particles.types = ['A']

snapshot.bonds.N = 1
snapshot.bonds.types = ['bond']
snapshot.bonds.typeid = [0]
snapshot.bonds.group = [(0,1)]

with gsd.hoomd.open(name='test.gsd', mode='wb') as f:
    f.append(snapshot)
sim.create_state_from_gsd(filename='test.gsd')

bond_potential = hoomd.md.bond.FENE()
bond_potential.params['bond'] = dict(k=30., r0=1.5, epsilon=1., sigma=1.)

#bond_potential = hoomd.md.bond.Harmonic()
#bond_potential.params['bond'] = dict(k=5000, r0=0.969)

integrator = hoomd.md.Integrator(dt=0.005)

integrator.forces.append(bond_potential)

nvt = hoomd.md.methods.Langevin(kT=1, filter=hoomd.filter.All(), alpha=0.1,seed=563)
integrator.methods.append(nvt)
sim.operations.integrator = integrator

sim.run(1)

```

## Output

```
Traceback (most recent call last):
  File "fene_min.hoomd", line 45, in <module>
    sim.run(1)
  File "/data/programs/hoomd-3.0.0/hoomd/simulation.py", line 328, in run
    self.operations._schedule()
  File "/data/programs/hoomd-3.0.0/hoomd/operations.py", line 196, in _schedule
    self.integrator._attach()
  File "/data/programs/hoomd-3.0.0/hoomd/md/integrate.py", line 193, in _attach
    super()._attach()
  File "/data/programs/hoomd-3.0.0/hoomd/md/integrate.py", line 55, in _attach
    self.forces._sync(self._simulation, self._cpp_obj.forces)
  File "/data/programs/hoomd-3.0.0/hoomd/data/syncedlist.py", line 154, in _sync
    item._attach()
  File "/data/programs/hoomd-3.0.0/hoomd/md/bond.py", line 36, in _attach
    super()._attach()
  File "/data/programs/hoomd-3.0.0/hoomd/md/force.py", line 53, in _attach
    super()._attach()
  File "/data/programs/hoomd-3.0.0/hoomd/operation.py", line 419, in _attach
    self._apply_typeparam_dict(self._cpp_obj, self._simulation)
  File "/data/programs/hoomd-3.0.0/hoomd/operation.py", line 449, in _apply_typeparam_dict
    typeparam._attach(cpp_obj, simulation)
  File "/data/programs/hoomd-3.0.0/hoomd/data/typeparam.py", line 42, in _attach
    sim)
  File "/data/programs/hoomd-3.0.0/hoomd/data/parameterdicts.py", line 214, in __init__
    self[key] = type_param_dict[key]
  File "/data/programs/hoomd-3.0.0/hoomd/data/parameterdicts.py", line 243, in __setitem__
    getattr(self._cpp_obj, self._setter)(key, val)
KeyError: 'lj1'
```

## Expected output

Working bond. Same script works fine if hoomd.md.bond.Harmonic() is used instead. 

## Configuration

Platform:
- Linux
- GPU

Installation method:
- Compiled from source (CUDA 10.1, gcc/g++ 8, no mpi)

Versions:
- Python version: 3.7.6 (anaconda)
- **HOOMD-blue** version: v3-beta.4

**Comment by joaander** [comment]
Thanks for the clear reproduction script. We'll get this fixed.
